# Generated by Django 2.1.7 on 2019-02-27 18:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gid', models.IntegerField(default=10)),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.TextField()),
                ('Opening_hours', models.TextField(blank=True, null=True)),
                ('Website', models.URLField(blank=True, null=True)),
                ('Tickets', models.TextField(blank=True, null=True)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('Geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
